config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :farmers, :controllers => {
    :registrations => 'farmer/registrations',
    :sessions => 'farmer/sessions',
    :passwords => 'farmer/passwords'
  }
  #  get '/farmers/sign_in' => 'farmar/sessions#new', as: :new_farmar_session
  #  post '/farmers/sign_in' => 'farmar/sessions#create', as: :farmar_session
  #  delete '/farmers/sign_out' => 'farmar/sessions#destroy', as: :destroy_farmar_session
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  #devise_scope :user do
  #  get "sign_in", :to => "users/sessions#new"
  #  get "sign_out", :to => "users/sessions#destroy" 
  #end
  #  get '/users/sign_in' => 'devise/sessions#new', as: :new_user_session
  #  post '/users/sign_in' => 'devise/sessions#create', as: :user_session
  #  delete '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  
  #get "top" => "home#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

<h1>ログインアプリ</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->

  <h4> メールアドレス： <%= current_user.email %> </h4>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% elsif farmer_signed_in? %>
  <h4> メールアドレス： <%= current_farmer.email %> </h4>
  <%= link_to "ログアウト", destroy_farmer_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "購入者ログイン", new_user_session_path, class: 'post' %> <!-- 購入者ログイン画面に移行する -->
  <%= link_to "購入者新規登録", new_user_registration_path, class: 'post' %> <!-- 購入者の新規登録画面に移行する -->
  <%= link_to "農家ログイン", new_farmer_session_path, class: 'post' %> <!-- 農家ログイン画面に移行する -->
  <%= link_to "農家新規登録", new_farmer_registration_path, class: 'post' %> <!-- 農家の新規登録画面に移行する -->
<% end %>